### ISSUE TITLE
Toast - customize theme and position

### ISSUE THREAD

**Issue by abotalebie** [fumeapp/tailvue#12]
Is there any way for customize toast theme and position?

**Comment by acidjazz** [comment]
@abotalebie there is nothing particular other than overriding the CSS classes yourself - you can see the defaults here https://github.com/fumeapp/tailvue/blob/main/src/toast.ts#L6-L14

**Comment by abotalebie** [comment]
My question is exactly the same.
How can I  override CSS classes?

**Comment by acidjazz** [comment]
well one idea: i set an `id` to the container element all of the toasts fire from [here](https://github.com/fumeapp/tailvue/blob/main/src/toast.ts#L24) - maybe you can do something like this:


```css
#toasts {
  @apply tailwind classes here;
}
```

or maybe go after the children:
```css
#toasts > div {
  @apply tailwind classes here;
}

please report back if you try this and it works - be great for the docs

**Comment by abotalebie** [comment]
Tanks, Yes It works

I applied the changes with the following codes for move toasts to bottom of page and apply RTL direction

```scss
#toasts {
  align-self: end;

  .mr-4 {
    margin-right: 0;
    margin-left: 1rem;
  }
  .ml-4 {
    margin-right: 1rem;
    margin-left: 0;
  }
  .ml-3 {
    margin-right: 0;
    margin-left: 0.75rem;
  }
}
```
But it would be better if there was a way to customize toasts position and classes.
Also, support for right-to-left mode is required.
